#!/bin/bash

###########################################################################
#
#	-Bash script to move/edit files:
#		+Sets device_id number in DeviceStatusLED.py
#		+Creates and starts service for running DeviceStatusLED.py
#
###########################################################################

# set device ID in script
read -p 'Please enter the device number: ' device_id
sed -i -e "s/DEVICE_ID = \"21\"/DEVICE_ID = \"$device_id\"/g" ./DeviceStatusLED.py
read -p 'Please enter your API key: ' api_key
sed -i -e "s/API_KEY = \"\"/API_KEY = \"$api_key\"/g" ./DeviceStatusLED.py

if [ ! -d "/path/to/dir" ] 
then
	mkdir /pi/home/DeviceStatusLED
fi

if cp ./DeviceStatusLED.py /pi/home/DeviceStatusLED/DeviceStatusLED.py 
then
	echo '033[0;42mMoved python script to /pi/home/DeviceStatusLED/\033[0;49m'
else
	echo '\033[0;31m***FAILED TO MOVE FILE TO /pi/home/DeviceStatusLED***\033[0;39m'
	echo 'The service will not work properly without the file being in this location or service path change'
fi


# setup service
if echo 'Device Status LED service:' \
	&& sudo cp ./DeviceStatusLED.service /etc/systemd/system/ \
	&& echo '\tSuccessfully moved' \
	&& sudo systemctl enable DeviceStatusLED.service \
	&& echo '\tSuccessfully enabled' \
	&& sudo systemctl start DeviceStatusLED.service \
	&& echo '\tSuccessfully started';
then
	echo '\033[0;42mSuccessfully created Device Status LED service\033[0;49m'
else
	echo '\033[0;31m***FAILED TO CREATE DEVICE STATUS SERVICE***\033[0;39m'
fi